name: aws_lambda_runtime
version: 1.1.1
description: |-
  A powerful runtime to build Lambda functions in Dart with native AWS events.
homepage: https://github.com/amondnet/aws-lambda-dart-runtime
#documentation: https://awslabs.github.io/aws-lambda-dart-runtime/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  json_annotation: ^4.9.0
  meta: ^1.16.0
  http: ^1.2.2

dev_dependencies:
  json_serializable: ^6.8.0
  build_runner: ^2.1.11
  test: ^1.25.8
  mockito: ^5.4.4
  pedantic: ^1.11.0
  lints: ^5.0.0