name: Page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: dart-lang/setup-dart@v1

      - name: Install Dart Doc
        run: dart pub global activate dartdoc

      - uses: actions/checkout@v2

      - name: Generate docs
        run: dartdoc --output doc

      - name: Create .nojekyll file
        run: |
          touch doc/.nojekyll
          touch .nojekyll

      - name: Publish GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
          enable_jekyll: false
